kind: IOConfig
implementation: mewbot.io.discord.DiscordIO
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa00
properties:
  token: "[token goes here]"

---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa01
properties:
  name: 'Echo Inputs'
triggers:
  - kind: Trigger
    implementation: examples.editor_warn_discord_bot.DiscordAllCommandTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa02
    properties:
      command: "!hello"
conditions: []
actions:
  - kind: Action
    implementation: examples.editor_warn_discord_bot.DiscordCommandTextAndEditResponse
    uuid: aaaaaaaa-aaaa-4aaa-0001-aaaaaaaaaa03
    properties:
      message: "world"
