apiVersion: v1
kind: IOConfig
module: mewbot.io.rss
name: RSSIO
uuid: 1
properties:
  sites: ["https://www.theguardian.com/world/rss", ]
  polling_every: 5

---

apiVersion: v1
kind: Behaviour
module: mewbot.api.v1
name: Behaviour
uuid: 1
properties:
  name: 'Echo Inputs'
triggers:
  - apiVersion: v1
    kind: Trigger
    module: examples.trivial_discord_bot
    name: DiscordTextCommandTrigger
    uuid: 1
    properties:
      command: "!hello"
conditions: []
actions:
  - apiVersion: v1
    kind: Action
    module: examples.trivial_discord_bot
    name: DiscordCommandTextResponse
    uuid: 1
    properties:
      message: "world"
