apiVersion: v1
kind: IOConfig
module: mewbot.io.rss
name: RSSIO
uuid: 1
properties:
  sites: ["https://www.theguardian.com/world/rss", "https://www.engadget.com/rss.xml" ]
  polling_every: 60

---


apiVersion: v1
kind: Behaviour
module: mewbot.api.v1
name: Behaviour
uuid: 1
properties:
  name: 'Echo Inputs'
triggers:
  - apiVersion: v1
    kind: Trigger
    module: mewbot.demo
    name: AllEventTrigger
    uuid: 1
    properties: { }
conditions: []
actions:
  - apiVersion: v1
    kind: Action
    module: examples.rss_input
    name: RSSPrintAction
    uuid: 1
    properties: { }

