kind: IOConfig
implementation: mewbot.io.rss.RSSIO
uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa00
properties:
  sites: ["https://www.theguardian.com/world/rss", "https://www.engadget.com/rss.xml" ]
  polling_every: 60

---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa02
properties:
  name: 'RSS Printer'
triggers:
  - kind: Trigger
    implementation: mewbot.demo.AllEventTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa03
    properties: { }
conditions: []
actions:
  - kind: Action
    implementation: examples.rss_input.RSSPrintAction
    uuid: aaaaaaaa-aaaa-4aaa-0000-aaaaaaaaaa04
    properties: { }
