kind: IOConfig
implementation: mewbot.io.socket.SocketIO
uuid: aaaaaaaa-aaaa-4aaa-0003-aaaaaaaaaa00
properties:
  host: localhost
  port: 12345

---

kind: Behaviour
implementation: mewbot.api.v1.Behaviour
uuid: aaaaaaaa-aaaa-4aaa-0003-aaaaaaaaaa01
properties:
  name: 'Echo Inputs'
triggers:
  - kind: Trigger
    implementation: mewbot.demo.AllEventTrigger
    uuid: aaaaaaaa-aaaa-4aaa-0003-aaaaaaaaaa02
    properties: { }
conditions: []
actions:
  - kind: Action
    implementation: mewbot.demo.PrintAction
    uuid: aaaaaaaa-aaaa-4aaa-0003-aaaaaaaaaa03
    properties: { }
